import os
import sys
from src.database.db_manager import DatabaseManager

# Ajouter le chemin parent au path pour importer les modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def seed_database():
    """
    Ajoute des données de test dans la base de données :
    - Aliments avec valeurs nutritionnelles
    - Repas types (recettes)
    - Un profil utilisateur par défaut
    """
    print("Initialisation de la base de données avec des données importées...")

    # Initialiser la base de données
    db = DatabaseManager()
    db.init_db()

    # ----------------------
    # Ajouter des aliments (95 aliments du fichier JSON)
    # ----------------------
    all_aliments = [
        {
            "nom": "Poulet (blanc)",
            "marque": "",
            "magasin": "Carrefour",
            "categorie": "Protéines",
            "calories": 165.0,
            "proteines": 31.0,
            "glucides": 0.0,
            "lipides": 3.6,
            "fibres": 0.0,
            "prix_kg": 9.9,
        },
        {
            "nom": "Thon au naturel",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 114.0,
            "proteines": 26.0,
            "glucides": 0.0,
            "lipides": 1.0,
            "fibres": 0.0,
            "prix_kg": 12.44,
        },
        {
            "nom": "Steak haché 5%",
            "marque": "Charal",
            "magasin": "Auchan",
            "categorie": "Protéines",
            "calories": 122.0,
            "proteines": 21.0,
            "glucides": 0.0,
            "lipides": 5.0,
            "fibres": 0.0,
            "prix_kg": 13.5,
        },
        {
            "nom": "Filet de saumon",
            "marque": "",
            "magasin": "Poissonnerie",
            "categorie": "Protéines",
            "calories": 208.0,
            "proteines": 20.0,
            "glucides": 0.0,
            "lipides": 13.0,
            "fibres": 0.0,
            "prix_kg": 19.9,
        },
        {
            "nom": "Riz blanc",
            "marque": "Taureau Ailé",
            "magasin": "Carrefour",
            "categorie": "Féculents",
            "calories": 356.0,
            "proteines": 7.0,
            "glucides": 79.0,
            "lipides": 0.5,
            "fibres": 1.4,
            "prix_kg": 2.5,
        },
        {
            "nom": "Pâtes complètes",
            "marque": "Panzani",
            "magasin": "Intermarché",
            "categorie": "Féculents",
            "calories": 348.0,
            "proteines": 12.0,
            "glucides": 65.0,
            "lipides": 2.5,
            "fibres": 8.5,
            "prix_kg": 3.2,
        },
        {
            "nom": "Pommes de terre",
            "marque": "",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 87.0,
            "proteines": 2.2,
            "glucides": 19.0,
            "lipides": 0.1,
            "fibres": 2.0,
            "prix_kg": 1.5,
        },
        {
            "nom": "Quinoa",
            "marque": "Céréal Bio",
            "magasin": "Biocoop",
            "categorie": "Féculents",
            "calories": 368.0,
            "proteines": 14.0,
            "glucides": 64.0,
            "lipides": 6.0,
            "fibres": 7.0,
            "prix_kg": 8.9,
        },
        {
            "nom": "Brocoli",
            "marque": "",
            "magasin": "Carrefour",
            "categorie": "Légumes",
            "calories": 34.0,
            "proteines": 2.8,
            "glucides": 7.0,
            "lipides": 0.4,
            "fibres": 2.6,
            "prix_kg": 2.5,
        },
        {
            "nom": "Carottes",
            "marque": "",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 41.0,
            "proteines": 0.9,
            "glucides": 10.0,
            "lipides": 0.2,
            "fibres": 2.8,
            "prix_kg": 1.2,
        },
        {
            "nom": "Courgette",
            "marque": "",
            "magasin": "Marché local",
            "categorie": "Légumes",
            "calories": 17.0,
            "proteines": 1.2,
            "glucides": 3.1,
            "lipides": 0.3,
            "fibres": 1.0,
            "prix_kg": 1.9,
        },
        {
            "nom": "Poivron rouge",
            "marque": "Vente libre",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 31.0,
            "proteines": 1.0,
            "glucides": 6.0,
            "lipides": 0.3,
            "fibres": 2.1,
            "prix_kg": 2.9,
        },
        {
            "nom": "Banane",
            "marque": "Vente libre",
            "magasin": "Leclerc",
            "categorie": "Fruits",
            "calories": 27.0,
            "proteines": 1.3,
            "glucides": 23.0,
            "lipides": 0.4,
            "fibres": 3.1,
            "prix_kg": 2.2,
        },
        {
            "nom": "Pomme",
            "marque": "",
            "magasin": "Marché local",
            "categorie": "Fruits",
            "calories": 52.0,
            "proteines": 0.3,
            "glucides": 14.0,
            "lipides": 0.2,
            "fibres": 2.4,
            "prix_kg": 2.5,
        },
        {
            "nom": "Myrtilles",
            "marque": "",
            "magasin": "Grand Frais",
            "categorie": "Fruits",
            "calories": 57.0,
            "proteines": 0.7,
            "glucides": 14.0,
            "lipides": 0.3,
            "fibres": 2.4,
            "prix_kg": 15.9,
        },
        {
            "nom": "Fraises",
            "marque": "",
            "magasin": "Marché local",
            "categorie": "Fruits",
            "calories": 32.0,
            "proteines": 0.7,
            "glucides": 7.7,
            "lipides": 0.3,
            "fibres": 2.0,
            "prix_kg": 5.9,
        },
        {
            "nom": "Ananas",
            "marque": "",
            "magasin": "Carrefour",
            "categorie": "Fruits",
            "calories": 50.0,
            "proteines": 0.5,
            "glucides": 13.0,
            "lipides": 0.1,
            "fibres": 1.4,
            "prix_kg": 3.5,
        },
        {
            "nom": "Fromage blanc 0%",
            "marque": "Danone",
            "magasin": "Intermarché",
            "categorie": "Produits laitiers",
            "calories": 54.0,
            "proteines": 8.0,
            "glucides": 4.0,
            "lipides": 0.1,
            "fibres": 0.0,
            "prix_kg": 3.2,
        },
        {
            "nom": "Lait écrémé",
            "marque": "Lactel",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 33.0,
            "proteines": 3.3,
            "glucides": 5.0,
            "lipides": 0.1,
            "fibres": 0.0,
            "prix_kg": 1.1,
        },
        {
            "nom": "Skyr",
            "marque": "Arla",
            "magasin": "Carrefour",
            "categorie": "Produits laitiers",
            "calories": 63.0,
            "proteines": 11.0,
            "glucides": 4.0,
            "lipides": 0.2,
            "fibres": 0.0,
            "prix_kg": 8.5,
        },
        {
            "nom": "Cottage cheese",
            "marque": "St Hubert",
            "magasin": "Monoprix",
            "categorie": "Produits laitiers",
            "calories": 98.0,
            "proteines": 11.5,
            "glucides": 2.4,
            "lipides": 4.3,
            "fibres": 0.0,
            "prix_kg": 12.8,
        },
        {
            "nom": "Amandes",
            "marque": "Couleur vives",
            "magasin": "Lidl",
            "categorie": "Noix & graines",
            "calories": 629.0,
            "proteines": 27.0,
            "glucides": 7.6,
            "lipides": 52.0,
            "fibres": 11.0,
            "prix_kg": 12.76,
        },
        {
            "nom": "Graines de chia",
            "marque": "Naturalia",
            "magasin": "Biocoop",
            "categorie": "Noix & graines",
            "calories": 486.0,
            "proteines": 17.0,
            "glucides": 42.0,
            "lipides": 31.0,
            "fibres": 34.0,
            "prix_kg": 16.5,
        },
        {
            "nom": "Noix de cajou",
            "marque": "",
            "magasin": "Carrefour",
            "categorie": "Noix & graines",
            "calories": 553.0,
            "proteines": 18.0,
            "glucides": 30.0,
            "lipides": 44.0,
            "fibres": 3.3,
            "prix_kg": 18.9,
        },
        {
            "nom": "Graines de tournesol",
            "marque": "",
            "magasin": "Naturalia",
            "categorie": "Noix & graines",
            "calories": 585.0,
            "proteines": 21.0,
            "glucides": 20.0,
            "lipides": 51.0,
            "fibres": 8.6,
            "prix_kg": 9.9,
        },
        {
            "nom": "Whey protéine",
            "marque": "MyProtein",
            "magasin": "En ligne",
            "categorie": "Suppléments",
            "calories": 412.0,
            "proteines": 82.0,
            "glucides": 7.5,
            "lipides": 7.5,
            "fibres": 0.0,
            "prix_kg": 30.0,
        },
        {
            "nom": "Créatine monohydrate",
            "marque": "Optimum Nutrition",
            "magasin": "En ligne",
            "categorie": "Suppléments",
            "calories": 0.0,
            "proteines": 0.0,
            "glucides": 0.0,
            "lipides": 0.0,
            "fibres": 0.0,
            "prix_kg": 60.0,
        },
        {
            "nom": "Protéine végétale",
            "marque": "SunWarrior",
            "magasin": "En ligne",
            "categorie": "Suppléments",
            "calories": 395.0,
            "proteines": 70.0,
            "glucides": 13.0,
            "lipides": 6.0,
            "fibres": 5.0,
            "prix_kg": 45.0,
        },
        {
            "nom": "Whey Chocolat",
            "marque": "BiotechUSA",
            "magasin": "En ligne",
            "categorie": "Compléments alimentaires",
            "calories": 380.0,
            "proteines": 73.0,
            "glucides": 6.1,
            "lipides": 6.5,
            "fibres": 0.0,
            "prix_kg": 27.4,
        },
        {
            "nom": "Whey Power Chocolat",
            "marque": "BiotechUSA",
            "magasin": "En ligne",
            "categorie": "Compléments alimentaires",
            "calories": 383.0,
            "proteines": 81.0,
            "glucides": 6.8,
            "lipides": 2.9,
            "fibres": 0.0,
            "prix_kg": 27.48,
        },
        {
            "nom": "Cruesli chocolat au lait",
            "marque": "Quaker",
            "magasin": "Leclerc",
            "categorie": "Sucreries",
            "calories": 472.0,
            "proteines": 7.4,
            "glucides": 62.0,
            "lipides": 20.0,
            "fibres": 7.4,
            "prix_kg": 5.71,
        },
        {
            "nom": "Fromage blanc 0%",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 47.0,
            "proteines": 7.3,
            "glucides": 4.4,
            "lipides": 0.0,
            "fibres": 0.0,
            "prix_kg": 1.89,
        },
        {
            "nom": "Lait matin léger",
            "marque": "Lactel",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 34.0,
            "proteines": 3.3,
            "glucides": 4.8,
            "lipides": 0.2,
            "fibres": 0.0,
            "prix_kg": 2.04,
        },
        {
            "nom": "Fruits rouges surgelés",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Fruits",
            "calories": 35.0,
            "proteines": 1.0,
            "glucides": 5.8,
            "lipides": 0.5,
            "fibres": 3.7,
            "prix_kg": 6.5,
        },
        {
            "nom": "Datte medjoul",
            "marque": "Epicerie",
            "magasin": "Leclerc",
            "categorie": "Fruits",
            "calories": 322.0,
            "proteines": 0.0,
            "glucides": 75.0,
            "lipides": 1.8,
            "fibres": 6.7,
            "prix_kg": 9.9,
        },
        {
            "nom": "Jambon blanc",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Viandes",
            "calories": 119.0,
            "proteines": 22.0,
            "glucides": 0.4,
            "lipides": 3.3,
            "fibres": 0.0,
            "prix_kg": 11.84,
        },
        {
            "nom": "Salade verte",
            "marque": "Eco+",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 15.0,
            "proteines": 1.0,
            "glucides": 2.0,
            "lipides": 0.1,
            "fibres": 1.3,
            "prix_kg": 2.0,
        },
        {
            "nom": "Olives vertes",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 593.0,
            "proteines": 0.9,
            "glucides": 0.0,
            "lipides": 15.0,
            "fibres": 2.8,
            "prix_kg": 5.94,
        },
        {
            "nom": "Cornichons",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 70.0,
            "proteines": 0.9,
            "glucides": 1.3,
            "lipides": 0.5,
            "fibres": 1.7,
            "prix_kg": 6.25,
        },
        {
            "nom": "Tartines céréales & graines",
            "marque": "La boulangère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 298.0,
            "proteines": 10.0,
            "glucides": 39.0,
            "lipides": 10.0,
            "fibres": 5.8,
            "prix_kg": 4.87,
        },
        {
            "nom": "Gros oeufs",
            "marque": "L'oeuf de nos villages",
            "magasin": "Leclerc",
            "categorie": "Viandes",
            "calories": 141.0,
            "proteines": 13.0,
            "glucides": 0.3,
            "lipides": 9.8,
            "fibres": 0.0,
            "prix_kg": 3.5,
        },
        {
            "nom": "Pâtes",
            "marque": "Panzani",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 361.0,
            "proteines": 12.0,
            "glucides": 72.0,
            "lipides": 2.0,
            "fibres": 0.0,
            "prix_kg": 1.88,
        },
        {
            "nom": "Filet de poulet",
            "marque": "Duc",
            "magasin": "Leclerc",
            "categorie": "Viandes",
            "calories": 110.0,
            "proteines": 23.4,
            "glucides": 0.0,
            "lipides": 1.5,
            "fibres": 0.0,
            "prix_kg": 9.95,
        },
        {
            "nom": "Crème épaisse SL",
            "marque": "Elle & vire",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 74.0,
            "proteines": 3.1,
            "glucides": 6.5,
            "lipides": 4.0,
            "fibres": 0.0,
            "prix_kg": 5.6,
        },
        {
            "nom": "Oignon",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 43.0,
            "proteines": 1.2,
            "glucides": 7.3,
            "lipides": 0.5,
            "fibres": 1.4,
            "prix_kg": 1.99,
        },
        {
            "nom": "Champignons de paris",
            "marque": "Eco+",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 19.0,
            "proteines": 2.2,
            "glucides": 0.6,
            "lipides": 0.4,
            "fibres": 2.1,
            "prix_kg": 4.75,
        },
        {
            "nom": "Maquereaux grillés",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 224.0,
            "proteines": 20.0,
            "glucides": 0.2,
            "lipides": 16.0,
            "fibres": 0.0,
            "prix_kg": 17.9,
        },
        {
            "nom": "Beurre 41%",
            "marque": "Elle & vire",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 384.0,
            "proteines": 0.3,
            "glucides": 3.2,
            "lipides": 41.0,
            "fibres": 0.5,
            "prix_kg": 8.28,
        },
        {
            "nom": "Canelle",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 247.0,
            "proteines": 4.0,
            "glucides": 80.0,
            "lipides": 1.2,
            "fibres": 0.0,
            "prix_kg": 25.0,
        },
        {
            "nom": "Huile d'olives",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 828.0,
            "proteines": 0.0,
            "glucides": 0.0,
            "lipides": 92.0,
            "fibres": 0.0,
            "prix_kg": 10.49,
        },
        {
            "nom": "Riz basmati",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 350.0,
            "proteines": 7.4,
            "glucides": 78.0,
            "lipides": 0.6,
            "fibres": 1.4,
            "prix_kg": 2.7,
        },
        {
            "nom": "Ail",
            "marque": "Label rouge",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 149.0,
            "proteines": 6.4,
            "glucides": 33.1,
            "lipides": 0.5,
            "fibres": 0.0,
            "prix_kg": 5.0,  # Valeur par défaut car null dans le JSON
        },
        {
            "nom": "Chapelure",
            "marque": "Tipiak",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 364.0,
            "proteines": 13.0,
            "glucides": 72.0,
            "lipides": 1.8,
            "fibres": 3.9,
            "prix_kg": 3.16,
        },
        {
            "nom": "Ciboulette",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 0.0,
            "proteines": 0.0,
            "glucides": 0.0,
            "lipides": 0.0,
            "fibres": 0.0,
            "prix_kg": 107.5,
        },
        {
            "nom": "Citron liquide",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 9.0,
            "proteines": 0.0,
            "glucides": 2.0,
            "lipides": 0.0,
            "fibres": 0.5,
            "prix_kg": 3.98,
        },
        {
            "nom": "Confiture de fraise allégées",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Sucreries",
            "calories": 164.0,
            "proteines": 0.5,
            "glucides": 40.0,
            "lipides": 0.5,
            "fibres": 1.0,
            "prix_kg": 3.18,
        },
        {
            "nom": "Crevettes",
            "marque": "Poissonerie",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 89.0,
            "proteines": 17.0,
            "glucides": 1.1,
            "lipides": 1.3,
            "fibres": 0.0,
            "prix_kg": 20.0,
        },
        {
            "nom": "Farine de blé",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Autre",
            "calories": 0.0,
            "proteines": 11.0,
            "glucides": 76.0,
            "lipides": 1.2,
            "fibres": 2.0,
            "prix_kg": 0.85,
        },
        {
            "nom": "Farine d'avoine",
            "marque": "Mon fournil",
            "magasin": "Leclerc",
            "categorie": "Autre",
            "calories": 370.0,
            "proteines": 13.0,
            "glucides": 60.0,
            "lipides": 6.7,
            "fibres": 9.7,
            "prix_kg": 8.5,
        },
        {
            "nom": "Haricots rouges",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 96.0,
            "proteines": 7.2,
            "glucides": 12.0,
            "lipides": 0.7,
            "fibres": 6.5,
            "prix_kg": 5.73,
        },
        {
            "nom": "Ketchup -70% sucre",
            "marque": "Heinz",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 44.0,
            "proteines": 1.6,
            "glucides": 5.4,
            "lipides": 0.4,
            "fibres": 0.0,
            "prix_kg": 3.8,
        },
        {
            "nom": "Kubor dégraissé",
            "marque": "Maggi",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 162.0,
            "proteines": 4.6,
            "glucides": 20.7,
            "lipides": 6.7,
            "fibres": 0.0,
            "prix_kg": 9.69,
        },
        {
            "nom": "Miel",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Sucreries",
            "calories": 316.0,
            "proteines": 1.0,
            "glucides": 78.0,
            "lipides": 0.0,
            "fibres": 0.0,
            "prix_kg": 6.46,
        },
        {
            "nom": "Noix",
            "marque": "Action",
            "magasin": "Action",
            "categorie": "Noix & graines",
            "calories": 707.0,
            "proteines": 15.9,
            "glucides": 5.4,
            "lipides": 68.0,
            "fibres": 7.0,
            "prix_kg": 13.0,
        },
        {
            "nom": "Pain burger",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 280.0,
            "proteines": 9.5,
            "glucides": 50.0,
            "lipides": 4.0,
            "fibres": 2.9,
            "prix_kg": 2.82,
        },
        {
            "nom": "Parmezan",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 402.0,
            "proteines": 32.0,
            "glucides": 0.0,
            "lipides": 30.0,
            "fibres": 0.0,
            "prix_kg": 16.5,
        },
        {
            "nom": "Persil",
            "marque": "Vente libre",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 36.0,
            "proteines": 3.0,
            "glucides": 6.3,
            "lipides": 0.8,
            "fibres": 3.3,
            "prix_kg": 19.8,
        },
        {
            "nom": "Pesto",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 312.0,
            "proteines": 3.7,
            "glucides": 5.3,
            "lipides": 30.0,
            "fibres": 3.0,
            "prix_kg": 7.84,
        },
        {
            "nom": "Poids chiche",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 123.0,
            "proteines": 5.7,
            "glucides": 16.0,
            "lipides": 2.2,
            "fibres": 6.7,
            "prix_kg": 2.25,
        },
        {
            "nom": "Pomme de terre",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 81.0,
            "proteines": 1.8,
            "glucides": 16.7,
            "lipides": 0.3,
            "fibres": 0.0,
            "prix_kg": 1.5,
        },
        {
            "nom": "Ricotta",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Produits laitiers",
            "calories": 155.0,
            "proteines": 8.0,
            "glucides": 6.0,
            "lipides": 11.0,
            "fibres": 0.0,
            "prix_kg": 5.16,
        },
        {
            "nom": "Sardine à l'huile d'olive",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 227.0,
            "proteines": 22.0,
            "glucides": 1.1,
            "lipides": 15.0,
            "fibres": 0.5,
            "prix_kg": 8.79,
        },
        {
            "nom": "Sauce tomate basilic",
            "marque": "Panzani",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 62.0,
            "proteines": 1.6,
            "glucides": 8.0,
            "lipides": 2.3,
            "fibres": 0.0,
            "prix_kg": 3.72,
        },
        {
            "nom": "Saumon fumé",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 165.0,
            "proteines": 21.0,
            "glucides": 0.0,
            "lipides": 9.0,
            "fibres": 0.5,
            "prix_kg": 24.15,
        },
        {
            "nom": "Saumon pavé",
            "marque": "Poissonerie",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 180.0,
            "proteines": 25.4,
            "glucides": 2.7,
            "lipides": 8.1,
            "fibres": 0.0,
            "prix_kg": 24.9,
        },
        {
            "nom": "Soja sauce",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 281.0,
            "proteines": 2.2,
            "glucides": 68.0,
            "lipides": 0.5,
            "fibres": 0.0,
            "prix_kg": 9.28,
        },
        {
            "nom": "Surimi",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 121.0,
            "proteines": 8.2,
            "glucides": 9.3,
            "lipides": 5.5,
            "fibres": 0.8,
            "prix_kg": 6.33,
        },
        {
            "nom": "Thon à la catalane",
            "marque": "Saupiquet",
            "magasin": "Leclerc",
            "categorie": "Poissons",
            "calories": 76.0,
            "proteines": 7.4,
            "glucides": 5.3,
            "lipides": 2.6,
            "fibres": 0.0,
            "prix_kg": 7.5,
        },
        {
            "nom": "Tomate concentrée",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 91.0,
            "proteines": 4.6,
            "glucides": 16.0,
            "lipides": 0.5,
            "fibres": 4.5,
            "prix_kg": 6.75,
        },
        {
            "nom": "Tomates rondes",
            "marque": "Vente libre",
            "magasin": "Leclerc",
            "categorie": "Légumes",
            "calories": 7.0,
            "proteines": 0.1,
            "glucides": 1.4,
            "lipides": 0.3,
            "fibres": 0.4,
            "prix_kg": 2.99,
        },
        {
            "nom": "Tortillas",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 331.0,
            "proteines": 9.3,
            "glucides": 54.0,
            "lipides": 8.0,
            "fibres": 3.0,
            "prix_kg": 5.28,
        },
        {
            "nom": "Feuille de lasagne",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Féculents",
            "calories": 357.0,
            "proteines": 12.0,
            "glucides": 71.0,
            "lipides": 1.8,
            "fibres": 3.3,
            "prix_kg": 2.78,
        },
        {
            "nom": "Vinaigre de vin",
            "marque": "Marque repère",
            "magasin": "Leclerc",
            "categorie": "Épices et condiments",
            "calories": 0.0,
            "proteines": 0.0,
            "glucides": 0.0,
            "lipides": 0.0,
            "fibres": 0.0,
            "prix_kg": 1.74,
        },
        {
            "nom": "Compote de pomme",
            "marque": "Andros",
            "magasin": "Leclerc",
            "categorie": "Sucreries",
            "calories": 54.0,
            "proteines": 0.3,
            "glucides": 16.0,
            "lipides": 0.1,
            "fibres": 0.0,
            "prix_kg": 2.27,
        },
        {
            "nom": "Épinards",
            "marque": "",
            "magasin": "Marché local",
            "categorie": "Légumes",
            "calories": 23.0,
            "proteines": 2.9,
            "glucides": 3.6,
            "lipides": 0.4,
            "fibres": 2.2,
            "prix_kg": 3.8,
        },
        {
            "nom": "Patate douce",
            "marque": "",
            "magasin": "Auchan",
            "categorie": "Féculents",
            "calories": 86.0,
            "proteines": 1.6,
            "glucides": 20.0,
            "lipides": 0.1,
            "fibres": 3.0,
            "prix_kg": 2.8,
        },
        {
            "nom": "Oeufs (L)",
            "marque": "",
            "magasin": "Leclerc",
            "categorie": "Protéines",
            "calories": 143.0,
            "proteines": 12.5,
            "glucides": 0.7,
            "lipides": 9.5,
            "fibres": 0.0,
            "prix_kg": 6.9,
        },
    ]

    # Ajouter les aliments à la base de données
    aliment_ids = {}  # Pour stocker les IDs des aliments ajoutés
    added_count = 0
    for aliment in all_aliments:
        try:
            # S'assurer que toutes les valeurs numériques sont présentes ou ont des valeurs par défaut
            for key in [
                "calories",
                "proteines",
                "glucides",
                "lipides",
                "fibres",
                "prix_kg",
            ]:
                if key not in aliment or aliment[key] is None:
                    aliment[key] = 0.0

            aliment_id = db.ajouter_aliment(aliment)
            aliment_ids[aliment["nom"]] = aliment_id
            added_count += 1
        except ValueError as e:
            print(
                f"⚠️ Erreur lors de l'ajout de l'aliment '{aliment.get('nom', 'inconnu')}': {e}"
            )

    print(f"✓ {added_count} aliments ajoutés")

    # ----------------------
    # Ajouter des repas types (recettes) du fichier JSON
    # ----------------------
    repas_types = [
        {
            "nom": "Fromage blanc protéiné avec cruesli et fruits",
            "description": "Petit-déjeuner équilibré riche en protéines et glucides complexes",
            "aliments": [
                {"nom": "Fromage blanc 0%", "quantite": 200},
                {"nom": "Whey Chocolat", "quantite": 15},
                {"nom": "Cruesli chocolat au lait", "quantite": 40},
                {"nom": "Lait matin léger", "quantite": 40},
                {"nom": "Fruits rouges surgelés", "quantite": 40},
            ],
        },
        {
            "nom": "Pâte poulet à la crème",
            "description": "Plat principal riche en protéines et glucides pour l'énergie",
            "aliments": [
                {"nom": "Pâtes", "quantite": 50},
                {"nom": "Filet de poulet", "quantite": 150},
                {"nom": "Crème épaisse SL", "quantite": 60},
                {"nom": "Champignons de paris", "quantite": 50},
                {"nom": "Oignon", "quantite": 20},
                {"nom": "Canelle", "quantite": 1},
            ],
        },
        {
            "nom": "Salade de riz",
            "description": "Repas équilibré, complet et rafraîchissant",
            "aliments": [
                {"nom": "Riz basmati", "quantite": 40},
                {"nom": "Olives vertes", "quantite": 15},
                {"nom": "Huile d'olives", "quantite": 5},
                {"nom": "Vinaigre de vin", "quantite": 5},
                {"nom": "Haricots rouges", "quantite": 25},
                {"nom": "Surimi", "quantite": 20},
                {"nom": "Gros oeufs", "quantite": 60},
                {"nom": "Cornichons", "quantite": 15},
                {"nom": "Thon au naturel", "quantite": 45},
            ],
        },
        {
            "nom": "Sandwich jambon et carré frais",
            "description": "Repas rapide et pratique, idéal pour le déjeuner",
            "aliments": [
                {"nom": "Tartines céréales & graines", "quantite": 75},
                {"nom": "Jambon blanc", "quantite": 120},
                {"nom": "Cornichons", "quantite": 25},
                {"nom": "Salade verte", "quantite": 20},
            ],
        },
        {
            "nom": "Shaker protéiné et lait",
            "description": "Collation riche en protéines idéale après l'entraînement",
            "aliments": [
                {"nom": "Whey Chocolat", "quantite": 30},
                {"nom": "Lait matin léger", "quantite": 250},
            ],
        },
    ]

    # Ajouter les recettes
    added_recipes = 0
    for recipe in repas_types:
        try:
            # Créer le repas type
            repas_type_id = db.ajouter_repas_type(recipe["nom"], recipe["description"])

            # Ajouter les aliments au repas type
            for aliment in recipe["aliments"]:
                if aliment["nom"] in aliment_ids:
                    aliment_id = aliment_ids[aliment["nom"]]
                    db.ajouter_aliment_repas_type(
                        repas_type_id, aliment_id, aliment["quantite"]
                    )
                else:
                    print(
                        f"⚠️ Aliment '{aliment['nom']}' non trouvé lors de l'ajout à la recette '{recipe['nom']}'"
                    )

            added_recipes += 1
        except ValueError as e:
            print(f"⚠️ Erreur lors de l'ajout de la recette '{recipe['nom']}': {e}")

    print(f"✓ {added_recipes} repas types (recettes) ajoutés")
    print("\nBase de données initialisée avec succès!")


if __name__ == "__main__":
    seed_database()
